### ISSUE TITLE
Long string patterns expand width of entire viewport

### ISSUE THREAD

**Issue by hackel** [jackwootton/json-schema#10]
When entering a very long string pattern, it expands the viewport beyond the browser width, requiring scrolling back and forth.  The overflow should be hidden when not actively editing the field to avoid this.  I suspect all the fields probably have this same issue, but I haven't encountered it yet.

**Comment by jackwootton** [comment]
Thanks for reporting this. Could you provide a screenshot and I 'll get on with fixing this.

**Comment by hackel** [comment]
![image](https://user-images.githubusercontent.com/583677/37259836-85b335cc-2583-11e8-8ec5-400afeb67821.png)

Hopefully this illustrates the issue.  I just noticed that there are actually two problems.  The most critical (to me) is that it expands the viewport, requiring horizontal scrolling (note it's scrolled all the way to the right in the screenshot).  The other minor issue is that the pattern is extending outside of the grey box surrounding it.  It's also wrapped to the next line.

What I would like to see is simply `"pattern": "^([\+-]?\d{4}(?!\d{2}\b))..." to indicate that it is longer and cut off, so that when I am done editing this field, I will still be able to see and click on the required checkbox for other fields, instead of having it pushed out of the window.  Hopefully that rambling made sense!

**Comment by jackwootton** [comment]
This is now fixed and deployed on https://www.jsonschema.net
