### ISSUE TITLE
Cannot find the support for String formats

### ISSUE THREAD

**Issue by nexxbizdev** [jackwootton/json-schema#11]
Hi,

I can't find the proper field in the UI, where string Formats (like date, date-time) can we configured?
http://json-schema.org/draft-07/json-schema-release-notes.html#formats

Cheers,
Omid

**Comment by jackwootton** [comment]
This will be released very soon...see screenshot below:

![screenshot from 2018-06-05 23-06-16](https://user-images.githubusercontent.com/1623996/41005399-2b0a1a7a-6915-11e8-9d11-61bb38e7efc0.png)

**Comment by jackwootton** [comment]
This is now live on the side. You can preset values using the menu on the LHS or in the edit view.

**Comment by paulostradioti** [comment]
I'm sorry, I still can't find where I can specify the format. Could you please provide some screenshot? 

Thank you so much,
Paulo

**Comment by evanjs** [comment]
Also having issues finding the format option.

Since we can't edit the schema directly, the only thing that works at the moment is copying the schema elsewhere and adding `format` manually, but it can get quite unwieldy with larger schemas.

**Comment by avinash-cn** [comment]
Same issue here. Can't find the format option.
