### ISSUE TITLE
In the editor, detail editor panes can get stuck partially off the bottom of the window

### ISSUE THREAD

**Issue by dls314** [jackwootton/json-schema#12]
When I'm editing towards the end of a schema, sometimes the detail pane used to edit things like examples or enums gets stuck off the bottom of the window.

When I remember to do so, I have to add some fake properties at the end of my example JSON to begin with so scrolling works right.

**Comment by jackwootton** [comment]
Thanks for flagging this. I too have hit this problem.  I new UI is being released soon where overlays will scroll in this scenario.

**Comment by jackwootton** [comment]
Edit panels now re-position themselves onto the screen if needed. The only slight problem now is the edit panel is no longer aligned with the schema after re-positioning. But, you can at least edit. Does this work well enough for you?

**Comment by dls314** [comment]
Works for me.
