### ISSUE TITLE
button to delete property

### ISSUE THREAD

**Issue by graingert** [jackwootton/json-schema#14]

**Comment by jackwootton** [comment]
Hi,

To clarify, do you mean a schema property (e.g. minLength, maxLength, required, etc) or a JSON property from the input?  If you're referring to a JSON property, and the delete button removes the JSON property and associated schema, what should happen the child properties (and thus child schemas)?

**Comment by graingert** [comment]
They get deleted also

**Comment by jackwootton** [comment]
I like it. Unfortunately it won't make it into the next update, but subsequent updates will be much smaller and more frequent. So I can imagine this being available in approximately 3 weeks. It's definitely not a big task and I will add it.

**Comment by jackwootton** [comment]
This is now available in GA.
