### ISSUE TITLE
[DEV site] exclusiveMinimum in Schema although set to false

### ISSUE THREAD

**Issue by cnbeining** [jackwootton/json-schema#16]
Using https://json-schema-dev.appspot.com/ on Jun.25:

Trying to load and edit Schema. exclusiveMinimum and exclusiveMaximum set to false via the left column(the settings button). On each number, exclusiveMinimum and exclusiveMaximum are set to false.

Click "preview code", the result is:

```
{
  "$id": "/properties/radius/properties/amount",
  "type": "number",
  "title": "The Amount Schema",
  "default": 0,
  "examples": [
    12.34
  ],
  "minimum": 0
}
```
 
but in the JSON Schema document generated, the number is still "exclusiveMinimum". 

Browser: Firefox OS: macOS

Such bug seems not exist on the original site, but the old site does not have Schema import so I am trying on the dev site.

**Comment by jackwootton** [comment]
@cnbeining  - So this is poor UX from me. The settings for JSON -> Schema are separate from Schema -> Schema (aka, loading a schema).

Right now, to get the new version out, I've disabled the Schema tab (i.e. options for loading a schema).

See the disabled 'Schema' tab below...this is intended for options relating to loading a schema. The 'JSON' tab is for JSON -> Schema generation only.

![screenshot from 2018-06-26 00-53-08](https://user-images.githubusercontent.com/1623996/41881419-5feeaee2-78db-11e8-9e09-066c0ae4084d.png)

Out of interest, what is effect do you expect the settings to have when loading an existing schema? Perhaps I can improve the UI and make this more useful for you.

**Comment by cnbeining** [comment]
Thanks for the reply.

As I am also new to JSON Schema so I may not have valuable input here: maybe we can expect 

- Global Enabled(disabled) field
- Default value
- Other global toggles.

Also let me know if you need server/computing power donation.

**Comment by jackwootton** [comment]
The new version is out the addresses the original problem here. If you still have missing features, please submit a new FR / issue.
