### ISSUE TITLE
[BUG] [SCHEMA OPTION] Big number and Float number trigger a whoops error.

### ISSUE THREAD

**Issue by eskignax** [jackwootton/json-schema#17]
Hello,

Here a small issue.

Inputted  number are not 'safely' managed.
if value is more than the max of an integer (2,147,483,647) it's trigger the whoops error
if value is a float (0.01) it's trigger the whoops error
If you use the arrow to change your number, it will transform your integer to a float and trigger the error for the same reason of above.

Thanks for this awesome tool :1st_place_medal:

**Comment by jackwootton** [comment]
This should not be working. Thanks for submitting this issue. Can you verify this works for you when you get a chance?

**Comment by jackwootton** [comment]
Tested with:

```
{
  "price": 2147483647
}
```

...results:

```
{
  "definitions": {}, 
  "$schema": "http://json-schema.org/draft-07/schema#", 
  "$id": "http://example.com/root.json", 
  "type": "object", 
  "title": "The Root Schema", 
  "required": [
    "price"
  ], 
  "properties": {
    "price": {
      "$id": "#/properties/price", 
      "type": "integer", 
      "title": "The Price Schema", 
      "default": 0, 
      "examples": [
        2147483647
      ]
    }
  }
}
```
