### ISSUE TITLE
Supply an existing json-schema

### ISSUE THREAD

**Issue by blag001** [jackwootton/json-schema#3]
Hello,
I can't find a way to edit an existing json-schema.

It seem I need to send the original JSON, and redo all the changes that was done on the json-schema.

Is there a way to do it ?

Thanks,
Blag

**Comment by jackwootton** [comment]
Not right now.  However, it's one of the most commonly requested features and should be in the next major release... about 3 weeks from now.  I hope this doesn't cause you too much inconvenience.

**Comment by blag001** [comment]
Yes, don't worry ;)

Would have be nice to have it, but I'll tell my collaborators to use a heavy client instead.
I'll try to keep my working version open.

If you don't mind, I'll  put issue for other enhancement.

**Comment by dls314** [comment]
In a similar track, is there a way to add a property as I'm editing a schema? I don't think so / know how to, so I end up adding a property to the json field which effectively starts over.

**Comment by blag001** [comment]
@jackwootton  nice, good luck with the development ;)

**Comment by zalizko** [comment]
So what the status of the request?

**Comment by jackwootton** [comment]
Currently testing in staging. This change is bundled with other changes which has delayed its release.  I'm aiming for a release in 1 week.

**Comment by jackwootton** [comment]
Deployment will, unfortunately, be pushed back to next weekend because a bug sucked-up my weekend.  To make-up for this I'm keeping an *old* version of `dev` running this week: https://json-schema-dev.appspot.com

...it's **not pretty** because it's my development version, but it may have the functionality you need to save yourself some time.

**Comment by jackwootton** [comment]
Now available. Check jsonschema.net
