### ISSUE TITLE
Unable to load generated schemas with minimum and maximum

### ISSUE THREAD

**Issue by DavidYawCSpeed** [jackwootton/json-schema#35]
Using the editor, I assign a minimum and maximum to a number field. If I take that generated schema and have the editor re-parse it, it fails to parse. 

Steps to reproduce:
1. Start with this schema, which defines an object with a basic number property. 
```
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "type": "number"
    }
  }
}
```
2. Using the editor, select the number field, and set the minimum to 3 and the maximum to 8. 
3. Go to one of the output tabs. Click the Copy To Clipboard button. It will copy this text. 
```
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "type": "number",
      "minimum": 3.0,
      "maximum": 8.0
    }
  }
}
```
4. Paste that same text into the schema editor on the left hand side, and click Load Schema. 

Result: Right hand side shows error icon with "Ooops"

**Comment by ltdeta** [comment]
+1

**Comment by sjswerdloff** [comment]
same is true for 
"type" : "integer"
but as of today, "minimum" functions as expected (on jsonschema.net).
"maximum" results in an oops...

**Comment by jackwootton** [comment]
fixed in the new version; www.jsonschema.net
