### ISSUE TITLE
Copy to clipboard function is copying number of lines too

### ISSUE THREAD

**Issue by luisfronquillo** [jackwootton/json-schema#37]
In online tool https://www.jsonschema.net, 'copy to clipboard' function is copying number of lines too.

![image](https://user-images.githubusercontent.com/18558207/48080566-f1ffb080-e1bb-11e8-9abd-cf3c1326c715.png)
-----
![image](https://user-images.githubusercontent.com/18558207/48080656-312e0180-e1bc-11e8-8dd2-f1a3bb0bd839.png)

And, i think, number of lines are not necessary in the copy.

**Comment by jackwootton** [comment]
Copying to clipboard while in the "Plain view" will not copy line numbers. You're using it the HTML view.

**Comment by AlexEshoo** [comment]
Copy to clipboard while in HTML view should also not copy line numbers, it is not intuitive at all.
