### ISSUE TITLE
Top of page button doesn't work

### ISSUE THREAD

**Issue by alexseguin** [jackwootton/json-schema#38]
![image](https://i.imgur.com/zRTPyRc.png)

This button seems to not be working on Chrome (I'm using V70).

**Comment by jackwootton** [comment]
The new version uses panels limited to the display height so there is no longer (a need for) a top button
![2020-01-08-213726_1878x948_scrot](https://user-images.githubusercontent.com/1623996/72018498-a8976f00-325f-11ea-999a-92d2a01fe286.png)

**Comment by jackwootton** [comment]
If you want to check this is fixed in the new version, you can do so at https://json-schema-dev.appspot.com/

**Comment by jackwootton** [comment]
fixed in the new version; www.jsonschema.net
