### ISSUE TITLE
How to hide the id attribute when generating rules?

### ISSUE THREAD

**Issue by rungao** [jackwootton/json-schema#39]
Dear,

First of all, I am very grateful to the online generator that provides the json schema, which is really very hard to design!

However, I have encountered a problem in use, please help me solve the problem, the problem is as follows:

When generating the schema specification, how do you not generate attributes with $id?

example:
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "username": {
      "type": "string"
    }
  }
}

**Comment by jackwootton** [comment]
Select "None" as ID type from the menu on the LHS, then generate you schema
