### ISSUE TITLE
Typo "minItems" ducplicates in schema array options

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [jackwootton/json-schema#40]
Hi! 
I have found two "minItems" in options of Json.Configuration.Array
But the second one should be "maxItems"
Please, fix this typo on your site https://jsonschema.net/#/
Attaching screenshot 
![image](https://user-images.githubusercontent.com/17043964/50403379-243a9100-07af-11e9-9c29-13b646cfe216.png)

Thank you and have a nice day!

**Comment by jackwootton** [comment]
Thanks for taking the time report this. I've just fixed this typo, and it will be visible in the next update (end of Jan 2019).

**Comment by aleksandr-kotlyar** [comment]
Hi. Great news, thank you. I am sure, that this fix will save time for others.

**Comment by jackwootton** [comment]
This is fixed in the new version now generally available; www.jsonschema.net
