### ISSUE TITLE
Support oneOf, allOf, etc.

### ISSUE THREAD

**Issue by edbrannin** [jackwootton/json-schema#44]
I tried loading a schema using oneOf, and those properties aren't shown in the generated schema.

(Or I did it wrong.  I looked for a "New Property" button in the UI to see if I was missing something, but I didn't see one.)

**Comment by flaphoschi** [comment]
Furthermore it seem to remove oneOf silently in the background, even when you don't modify anything.

**Comment by jackwootton** [comment]
Fixed in the new version; www.jsonschema.net
