### ISSUE TITLE
Changing "items per page" or going to another page messes up some attributes

### ISSUE THREAD

**Issue by SergeyMokhov** [jackwootton/json-schema#45]
**Steps to reproduce**
- Load Schema that is larger than one page
- On the right side click on the pencil sign to edit schema
- On item that has type string remove pattern
- Create one item that has default  = null
- Change items per page or click back and forth buttons

**Expected result**
- All the data unchanged

**Actual result**
- Pattern is back
- default is "" or 0

**Comment by jackwootton** [comment]
This is fixed in the new version now generally available; www.jsonschema.net
