### ISSUE TITLE
[UI] mat-toolbar element blocks interaction with the scrollbar

### ISSUE THREAD

**Issue by Looooong** [jackwootton/json-schema#46]
The `mat-toolbar` element prevents clicking on the scrollbar (green zone).
Browser: Chrome 74.0.3729.108

![Screenshot from 2019-04-25 15-40-11](https://user-images.githubusercontent.com/8206622/56722137-9a0c3480-6770-11e9-801e-1bd3510d2eba.png)

**Comment by jackwootton** [comment]
If you want to check this is fixed in the new version, you can do so at https://json-schema-dev.appspot.com/

**Comment by Looooong** [comment]
LGTM :+1:
