### ISSUE TITLE
I hit tab and ALL my data is gone unrecoverable, 

### ISSUE THREAD

**Issue by Kdhunt** [jackwootton/json-schema#47]
This has happened to me 8 times trying to use this tool.  
If Im at the end of a line and entering data, or sometimes on a new line, but I tab and it simply wipes out everything Ive already entered, this is IMMENSLY frusterating, and literally makes the tool unusable for me.

**Comment by jackwootton** [comment]
Yeah, that sounds pretty bad. And I can see why it basically makes the tool unusable. Could you explain where you enter data? Is it when adding JSON, or when editing a schema in the edit view?

**Comment by jackwootton** [comment]
If you want to check this is fixed in the new version, you can do so at https://json-schema-dev.appspot.com/

**Comment by jackwootton** [comment]
This is fixed in the new version now generally available; www.jsonschema.net
