### ISSUE TITLE
ID type cannot be selected

### ISSUE THREAD

**Issue by pboettch** [jackwootton/json-schema#48]
According to #35 omitting `$id`-attributes can be done by select ID-type None in the LHS-menu. 

I'm unable to find this option in the menu. In which section is it located?

**Comment by jackwootton** [comment]
Click the hamburger menu in the top left to open the side nav. From there you should find options for URI fragment:

<img width="679" alt="Screen Shot 2019-05-26 at 12 06 09 AM" src="https://user-images.githubusercontent.com/1623996/58375402-31b89a80-7f4a-11e9-9737-3c7f71f7ee8b.png">
