### ISSUE TITLE
Handle multi-value for the exemple field

### ISSUE THREAD

**Issue by blag001** [jackwootton/json-schema#5]
In the example JSON : 

```
  "tags": [
    "home",
    "green"
  ]
```

Only produce this JSON Schema output : 
```
        "examples": [
          "home"
        ]
```

Could be a good idea to set a 3 values by default and allow user to chose how much example he want.

**Comment by jackwootton** [comment]
This should now be live. When you have a moment, could you let me know if it meets your expectations? Note, examples are only provided for primitive values (original behaviour).

**Comment by blag001** [comment]
Seem to work for me.
You didn't put a limit on the number of example that'll be shipped ?

ps: Monokai is live too, good job °¬°

**Comment by jackwootton** [comment]
I'll have to work out the UI for that.  Right now, zero no examples or all examples should be fine for most people.

**Comment by jackwootton** [comment]
Feel free to close this if it meets your needs.

**Comment by blag001** [comment]
That'll do perfectly fine, no worry ;)
