### ISSUE TITLE
Breaks on large input

### ISSUE THREAD

**Issue by mvrozanti** [jackwootton/json-schema#50]
The JSON I'm providing is valid, tested [like so](https://stackoverflow.com/questions/46954692/check-if-string-is-a-valid-json-with-jq), and yet I get a red text label displaying "Your JSON*" which I presume indicates the JSON is invalid.

Also, is the source code public?

**Comment by jackwootton** [comment]
Is this still a problem for you on the new version; www.jsonschema.net

**Comment by mvrozanti** [comment]
I don't need this anymore so I can't really tell. Good luck though!
