### ISSUE TITLE
Schema is copying with line numbers

### ISSUE THREAD

**Issue by akimkelar** [jackwootton/json-schema#51]
Schema is copying with line numbers.
This behavior corrupts the schema (where numbers as examples are present).

**Comment by aaronhuggins** [comment]
@akimkelar Sounds like you're copying from the styled view. You should copy from the text-only view. There are tabs at the top which allow edit, text-only, and styled. Choose the middle one when copying the schema from the page and it will do so with no styling or line numbers.

**Comment by czieglerAC** [comment]
I would like it if the styled view copy did not copy line numbers - it doesn't seem to me like there would be a use case where you would ever want to copy the line numbers, and this is the default view so it would be nice to not have to switch to a different tab. Just a suggestion!

**Comment by jackwootton** [comment]
Good point. My thinking was for documentation purposes (i.e. "on line 4"...). I wonder if I can make this clearer without losing flexibility.

**Comment by stevensouza** [comment]
can you display the numbers but just never copy them?  then you could also get rid of text-only view and simplify the interface further.  

Thanks for this tool, saved me lots of time and validated perfectly the first time, unlike another site I tried.

**Comment by czieglerAC** [comment]
I think it would be enough to have the "default" tab be the text-only tab - then you can quickly copy your schema without line numbers. Thanks!

**Comment by jackwootton** [comment]
This has changed in the new version where line numbers will not be copied
![2020-01-08-213726_1878x948_scrot](https://user-images.githubusercontent.com/1623996/72018421-830a6580-325f-11ea-9dc4-7c7f68d4450d.png)

**Comment by jackwootton** [comment]
YW. If you want to check this is fixed in the new version, you can do so at https://json-schema-dev.appspot.com/

**Comment by jackwootton** [comment]
This is fixed in the new version now generally available; www.jsonschema.net
