### ISSUE TITLE
Detail editor panes are pushed off the bottom of the window

### ISSUE THREAD

**Issue by JoBrad** [jackwootton/json-schema#52]
Possibly a regression of #12. Tested in Chrome 75.0.3770.142 and Firefox 68.0.1.

When adding enum values the enum fields start at the top of the `app-overlay-footer` element, and quickly get pushed off panel. I think it's a problem with the the way the `app-list-value` element is added to the `overlay-content` parent div, but not totally sure.

**Comment by jackwootton** [comment]
This has changed in the new version which uses a much larger model window:

![2020-01-08-213933_1877x947_scrot](https://user-images.githubusercontent.com/1623996/72018345-6110e300-325f-11ea-8fae-db800c1b7bd0.png)

**Comment by jackwootton** [comment]
YW. If you want to check this is fixed in the new version, you can do so at https://json-schema-dev.appspot.com/

**Comment by jackwootton** [comment]
Closing as this is fixed on www.jsonschema.net
