### ISSUE TITLE
When the JSON has errors and the focus is lost from the editor, the complete json is erased

### ISSUE THREAD

**Issue by ppazos** [jackwootton/json-schema#54]
It doesnt work to lose all the format because it is invalid, just because you need to copy some text from another application.

**Comment by jackwootton** [comment]
+1 This is *really* bad, and thank you for reporting it. I'm going to look at improving this in the new version.

**Comment by jackwootton** [comment]
If you want to check this is fixed in the new version, you can do so at https://json-schema-dev.appspot.com/

**Comment by jackwootton** [comment]
Closing as this is fixed on www.jsonschema.net
