### ISSUE TITLE
Setting format date-time on a property and then rendering the schema says format: null

### ISSUE THREAD

**Issue by ppazos** [jackwootton/json-schema#55]

**Comment by jackwootton** [comment]
Confirmed this is an issue and thanks for reporting. In the new version (scheduled for release this year) semantic validation options get their own "card" in the schema options and I have confirmed this bug is not present.

**Comment by jackwootton** [comment]
This feature is not yet available on the new version of www.jsonschema.net so I'm closing this. However, this feature will be landing soon. Thank you for reporting this.
