### ISSUE TITLE
Copy to clipboard, copies also the line numbers

### ISSUE THREAD

**Issue by ppazos** [jackwootton/json-schema#56]

**Comment by timini** [comment]
anyone know how to get round this one?

**Comment by timini** [comment]
I found out it works in plain text mode

**Comment by jackwootton** [comment]
Yeah, the different views allow users to copy with and without line numbers.  Is there any way I can make this clearer? You're not the first to hit this problem!

**Comment by RetroSwimAU** [comment]
I don't know if there's a use-case where copying the line numbers is useful? Other sites that show line numbers (like pastebin) omit line numbers when highlighting and copying text to clipboard, so this is probably how people expect it to work.

If being able to include line numbers is important, perhaps add that text to the button's tooltip, like "Copy with Line Numbers" or something?

**Comment by jackwootton** [comment]
This has changed in the new version so line numbers will not be copied.

![2020-01-08-213726_1878x948_scrot](https://user-images.githubusercontent.com/1623996/72018228-2b6bfa00-325f-11ea-9083-85bafba46997.png)

**Comment by RetroSwimAU** [comment]
Nice!! Thank you for your hard work on this tool, it's been super useful! :)

**Comment by jackwootton** [comment]
YW. If you want to check this is fixed in the new version, you can do so at https://json-schema-dev.appspot.com/

**Comment by jackwootton** [comment]
Closing as this is fixed on www.jsonschema.net.
