### ISSUE TITLE
Invalid JSON handling with error message

### ISSUE THREAD

**Issue by saintlyzero** [jackwootton/json-schema#57]
**Invalid JSON entered gets completely removed when the focus is changed.**
----
Improvements:

- Display a pop-up or a label indicating 'Invalid JSON'
- Highlight the line number having an error

**Comment by dsbert** [comment]
This is extremely annoying because I find myself pushing `tab` to indent the next line, which is currently invalid due to a trailing comma on the previous line. This causes the editor to lose focus and wipe out everything I just entered. After doing this 3 times in a row, I closed the tab.

**Comment by jackwootton** [comment]
Closing as this is fixed on www.jsonschema.net
