### ISSUE TITLE
[editor] deep over 5 break the padding

### ISSUE THREAD

**Issue by blag001** [jackwootton/json-schema#6]
When using a JSON of more than 5 deep, on the `EDIT` screen the 6th node is at the same padding than the the root node.

If there is a way to improve the readability of this (horizontal scroll ? going back to a root+1 padding but with a color/ branch to point it's a child ?)

![editor break](https://user-images.githubusercontent.com/6142277/36570541-d998818c-1832-11e8-952f-ab2a8ff1ce77.png)

Here is the JSON used : 
`{"d1":[{"d2":[{"d3":[{"d4":[{"d5":[{"d6":[{"d7":[{"d8":[]}]}]}]}]}]}]}]}`

**Comment by jackwootton** [comment]
Thanks for supply the JSON - really helped. This should now be fixed.

**Comment by blag001** [comment]
Yes, solved !
