### ISSUE TITLE
Can json-schema generate draft 4?

### ISSUE THREAD

**Issue by stevensouza** [jackwootton/json-schema#61]
Is there a way to define what JSON schema draft you generate?  The site generates draft7. I am using a Java API that only supports draft 4.  In my case, I was able to simply change the $schema to the following and it worked though I am not sure I would always be that lucky.

`"$schema": "http://json-schema.org/draft-04/schema#",
`

**Comment by kiranch2004** [comment]
Website does not work from me after deleting cookies... did something change after Nov 1st. 
let me see if I can make this work.

**Comment by jackwootton** [comment]
The new version is now generally available on https://www.jsonschema.net

Are you experiencing the same problem there too?

**Comment by jackwootton** [comment]
Please use the settings panel

![image](https://user-images.githubusercontent.com/1623996/75630294-61838580-5be1-11ea-9692-cc632ab4acb7.png)
