### ISSUE TITLE
Schema generation failing

### ISSUE THREAD

**Issue by wgcostello** [jackwootton/json-schema#62]
When users in our firm select "Infer Schema" on this application, they encounter an error saying that the schema generation has failed. This happens regardless of what JSON they enter on the left-hand side.

We operate under a firewall hosted by Palo Alto Networks, however I have also tried this with firewall exceptions and run into the same issue. Is there anything that needs to be unblocked in order for this application to work for us?

![2019-12-05_11-51-37](https://user-images.githubusercontent.com/43070867/70233026-a8362080-1755-11ea-9ca7-eac117873459.png)

**Comment by jackwootton** [comment]
Do you experience the same issue on https://json-schema-dev.appspot.com ?

**Comment by eskignax** [comment]
> Do you experience the same issue on https://json-schema-dev.appspot.com ?

I have the same issue as wgcostello, I am using Brave navigator and I might be behind a firewall too.

It's working well on:
https://json-schema-dev.appspot.com

**Comment by jackwootton** [comment]
The new version is now generally available on https://www.jsonschema.net
