### ISSUE TITLE
Request: JSON sample, Response: JSON schema API possible?

### ISSUE THREAD

**Issue by SeaDude** [jackwootton/json-schema#63]
Hello,
This is a killer tool, nice work! The UI has more schema features than I know how to use (awesome!). Is it possible to send a JSON sample via API to your app and receive the JSON schema? If so, what are the specs?
Thank you

**Comment by jackwootton** [comment]
@SeaDude - There is a REST API, although it's not currently generally available (a few companies have expressed an interest). The API exposes the following methods

- DeleteSchema (HTTP DELETE)
- GetDocument (HTTP GET)
- InferDocument (HTTP POST)
- LoadDocument (HTTP POST)
- UpdateSchema (HTTP PATCH)

The main _resources_ are

- Schema
- SchemaDocument
- SchemaGraph

The new version of JSONschema.net (also not generally available yet) is being tested by a few users at https://json-schema-dev.appspot.com. A lot of the options have gone away to keep it simple). However there are new features like `examples` and `default` keywords working with `object` and `array` types.

**Comment by SeaDude** [comment]
Thanks for the response @jackwootton. I'd love to test the API if it becomes generally available. Will peek at the new version of JSONschema.net too. 
Take care

**Comment by parjanyaroy** [comment]
@jackwootton First of all, kudos for the epic tool !!! I was looking for something similar to what @SeaDude had asked. I couldn't find any options in www.jsonschema.net. Has the API been made available yet?
