### ISSUE TITLE
JSON Schema Tool content error on label

### ISSUE THREAD

**Issue by dc-avasilev** [jackwootton/json-schema#64]
Hello, you have a content error on site, in Array section, need to be a min and max, by now it’s min and min
 
[plz fix it](https://cloud.mail.ru/public/2Gdh/2Pd83PYQ5)

**Comment by jackwootton** [comment]
Thanks for letting me know. Issues with the current version won't be fixed because the new version isn't far away: https://json-schema-dev.appspot.com

**Comment by jackwootton** [comment]
The new version is now generally available on https://www.jsonschema.net
