### ISSUE TITLE
[BUG] Referer address is blocked by the API key Restrictions.

### ISSUE THREAD

**Issue by eskignax** [jackwootton/json-schema#65]
https://jsonschema.net/home

Just trying to make the demo sample work.
Navigator : Brave
OS : Fedora

Error display in red at the first try : 
`Referer address is blocked by the API key Restrictions.`

If try a second time, it's loading for ever.

**Comment by jackwootton** [comment]
I will test this for myself later. To speed this up, does this work in a non-Brave browser? I just went to workout if it's Brave or a network issue.

And thanks for taking the time to raise this bug.

**Comment by jackwootton** [comment]
I tested this:

Navigator: **Brave 1.4.95**, Chromium: 80.0.3987.122 (Official Build) (64-bit)
OS: **Ubuntu 18.04** bionic (x86-64)

It worked for me, but I did have to "Shields DOWN for this site". See https://support.brave.com/hc/en-us/articles/360022806212-How-do-I-use-Shields-while-browsing-

**Comment by eskignax** [comment]
it works fine with the shield down. Sorry I should have tested that.
Version 1.0.1 not the last one I think I am keeping having issue with the update unfortunately.

**Comment by jackwootton** [comment]
Can I close this, or do you need me to look into this further?
