### ISSUE TITLE
Copy to clipboard not works

### ISSUE THREAD

**Issue by bestwebua** [jackwootton/json-schema#68]
Hello! First of all thanks for this awesome service! In a new version button `Copy to clipboard` not works.

![Screenshot from 2020-03-03 16-52-25](https://user-images.githubusercontent.com/14002692/75787485-78f07900-5d6f-11ea-8d91-71cbec3af7f6.png)

**Comment by jackwootton** [comment]
This works for me. Can you provide your browser + platform details? Also, is there any output in the debug console that you can paste here?

**Comment by bestwebua** [comment]
@jackwootton, yup: Mozilla Firefox 73.0.1 (64-bit), Ubuntu 19.10.
```bash
document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.

(3) vendor.265e3f6898ea7641add0.js:8186:44
```

**Comment by jackwootton** [comment]
@bestwebua thanks. Looks like someone else has reported thisL https://github.com/angular/components/issues/18449

**Comment by bestwebua** [comment]
@jackwootton, you're welcome!

**Comment by bestwebua** [comment]
It seems that material clipboard action has been fixed. So 'copy to clipboard' action works like a charm.

**Comment by jackwootton** [comment]
@bestwebua thanks for updating this. The weird thing is, I haven't deployed an updated version of Angular, so was this fix in Firefox?

**Comment by bestwebua** [comment]
@jackwootton, exactly:) Mozilla Firefox has been updated up to 74.0 version. Thanks for your time!
