### ISSUE TITLE
setting in safari broken

### ISSUE THREAD

**Issue by harDsantosa** [jackwootton/json-schema#69]
<img width="1637" alt="image" src="https://user-images.githubusercontent.com/51914595/75839369-455b3080-5dfb-11ea-85df-df9bab566071.png">
this displays setting when open with browser safari

**Comment by harDsantosa** [comment]
fixed

**Comment by jsonsystems** [comment]
@harDsantosa this is now fixed. Thanks for taking the time to report it.
