### ISSUE TITLE
Why having a dedicated save button ?

### ISSUE THREAD

**Issue by blag001** [jackwootton/json-schema#7]
I was first thinking the editor was broken, but in fact you had to save before changing the view from `EDIT` to `HTML`.

Why having a button ? 
Why not making continuous save, as it's usually done with web application, with an `onChange{save()}` ?

ps : I put a lot of Issues, but only my #3  is really a priority for me. You've done pretty well for now, I just give you the few missing feature that, I think, will make it awesome ;)

**Comment by jackwootton** [comment]
Continuous save is coming. Originally the reason for the dedicated button was to prevent large amounts of data being transferred unnecessarily. Some users have very large JSON and JSON Schema and a background approach would require regenerating HTML and PLAIN views upon every change.

However, it is something I have planned shortly and I agree, background saving would be better!

**Comment by blag001** [comment]
Nice ;)
If you're afraid of DDOS-ing your server, you can choose a save on change tab (to `HTML` or `PLAIN`) and a background task every 20s that check if you need to save (like most webmail editor do).

BTW, you're not using a client side processing ? (that could be great, everything in JS, nearly offline ready °¬°)

**Comment by hackel** [comment]
I just got hit with this myself, losing all my work.  It's okay if you can't implement it right away, but *please* add a warning dialogue when navigating to another tab without saving!

**Comment by jackwootton** [comment]
I'm very sorry you lost your work because of a poor UI / UX. I'm actually very close to releasing background updating - however I should have prioritized adding an alert. That's my fault. 

As I said, this is being released very soon.

**Comment by jackwootton** [comment]
No more save button. Now available in the new version.
